language: generic

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"

install:
    - mkdir -p ${HOME}/cache/pkgs
    - wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh
    - bash miniforge.sh -b -p ${CONDA_INSTALL_LOCN} && export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH

    # Re-use the packages in the cache, and download any new ones into that location.
    - rm -rf ${CONDA_INSTALL_LOCN}/pkgs && ln -s ${HOME}/cache/pkgs ${CONDA_INSTALL_LOCN}/pkgs

    # Configure Bot account.
    - git config --global user.name "Travis-CI on github.com/conda-forge/blog"
    - git config --global user.email conda.forge.coordinator@gmail.com

    # Update conda.
    - conda update --yes --quiet conda

    # Configure conda.
    - conda config --set show_channel_urls true
    - conda config --set auto_update_conda false
    - conda config --prepend channels conda-forge

    # install stuff
    - conda install --file requirements.txt --yes --quiet

script:
    - echo "Updating docs";
    - bash ./.ci_scripts/update_docs;
